04-Projeto de Interface.md / Adicionado Diagrama de Fluxo
ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e2-proj-int-t6-repoinsight pull request #25
Opened 2024-03-26 19:39 UTC by Victor-Ornelas-Code

Adicionado diagramas de Fluxo

2024-04-01 05:13 UTC, fabiobarkoski commented
Achei muito bom assim, com cada fluxo separado e ainda podendo entender quando faz referências a outros fluxos

2024-04-01 05:14 UTC, fabiobarkoski requested changes
gostei

2024-04-01 05:14 UTC, fabiobarkoski commented on docs/04-Projeto de Interface.md
> +> ![Fluxo de Cadastro](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e2-proj-int-t6-repoinsight/assets/80174882/84311872-55e0-4d63-b467-6645a742214a)
Acho que aqui poderia ser "email e senha validos?", ao invés de apenas email

2024-04-12 03:15 UTC, thiago-lc approved these changes

2024-04-12 11:46 UTC, Victor-Ornelas-Code commented on docs/04-Projeto de Interface.md
> +> ![Fluxo de Cadastro](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e2-proj-int-t6-repoinsight/assets/80174882/84311872-55e0-4d63-b467-6645a742214a)
Corrigido Fluxo de Cadastro

2024-04-12 19:38 UTC, fabiobarkoski approved these changes

2024-04-12 19:38 UTC, merged