doc: Adicionar diagrama de classes
ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e2-proj-int-t6-repoinsight pull request #31
Opened 2024-04-04 00:47 UTC by gustavompc

Criado o diagrama de classes.

2024-04-08 04:05 UTC, fabiobarkoski requested changes
Acho que me equivoquei na hora de criar a tabela projetos e em alguns pontos, vou pôr em itens aqui:
- [ ] retirar a tabela projetos e renomear a projeto/github para projetos
- [ ] retirar id das tabelas
- [ ] na tabela projeto/github, por uma identificação do projeto, como o nome dele
- [ ] na tabela projeto/github, retirar a dataInicio, acho que não precisamos disso
- [ ] na tabela usuário, podemos trocar os 4 métodos por apenas registrar e logar
- [ ] na tabela usuário, podemos inserir os métodos que estão na projetos, o adicionarProjeto, removerProjeto e filtar
- [ ] na tabela usuário, já que vamos ter os métodos dos projetos. podemos ter um campo projetos, do qual vai ter os projetos
- [ ] na tabela usuário, acho que podemos trocar de enderecoDeEmail para apenas email

2024-04-09 22:47 UTC, LucasRiboli commented
Deve conter todo os requisitos funcionais como métodos dentro do diagrama de classe.

2024-04-10 23:43 UTC, fabiobarkoski commented
> Acho que me equivoquei na hora de criar a tabela projetos e em alguns pontos, vou pôr em itens aqui:
Atualizacoes realizadas

2024-04-11 02:04 UTC, LucasRiboli approved these changes
LGTM

2024-04-11 02:27 UTC, fabiobarkoski approved these changes

2024-04-11 02:27 UTC, merged